platform :ios, '7.0'

pod 'ShareSDK2'
pod 'ShareSDK2/UI/iPhoneDefault'
pod 'ShareSDK2/Connection/SinaWeibo'
pod 'ShareSDK2/Connection/WeChat'
pod 'ShareSDK2/Connection/QQ'
pod 'ShareSDK2/Connection/QZone'
pod 'ShareSDK2/Connection/SMS'
pod 'MOBFoundation'
